# Generated by Django 4.2.7 on 2025-01-27 16:50

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('status', models.CharField(choices=[('A', 'Available'), ('S', 'Sold')], max_length=1)),
            ],
        ),
    ]
