# Generated by Django 5.1.5 on 2025-01-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_auction_bidder_alter_auction_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
