# Generated by Django 5.1.5 on 2025-01-30 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 18, 55, 36, 671015, tzinfo=datetime.timezone.utc)),
        ),
    ]
