# Generated by Django 5.1.5 on 2025-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_notification_is_read_alter_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='heading',
            field=models.CharField(default='Notification', max_length=100),
        ),
    ]
