# Generated by Django 5.1.5 on 2025-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_notification_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creared_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
