# Generated by Django 4.2.7 on 2025-01-27 16:56

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
