# Generated by Django 5.1.5 on 2025-04-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_notification_creared_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
