# Generated by Django 4.2.7 on 2025-01-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
    ]
