# Generated by Django 5.1.5 on 2025-01-31 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auction_winner_alter_auction_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 20, 7, 6, 964575, tzinfo=datetime.timezone.utc)),
        ),
    ]
