# Generated by Django 5.1.5 on 2025-02-01 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_owner_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 14, 5, 8, 17459, tzinfo=datetime.timezone.utc)),
        ),
    ]
