# Generated by Django 5.1.5 on 2025-02-01 13:08

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=product.models.get_default_end_time),
        ),
    ]
